//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_Carros.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VentaDeCarrosTallerEntities1 : DbContext
    {
        public VentaDeCarrosTallerEntities1()
            : base("name=VentaDeCarrosTallerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Detalle_Factura> Detalle_Factura { get; set; }
        public virtual DbSet<Detalle_Repuestos_Orden> Detalle_Repuestos_Orden { get; set; }
        public virtual DbSet<Detalle_Servicios> Detalle_Servicios { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Garantia> Garantias { get; set; }
        public virtual DbSet<Historial_Vehiculos> Historial_Vehiculos { get; set; }
        public virtual DbSet<Inventario_Repuestos> Inventario_Repuestos { get; set; }
        public virtual DbSet<Ordenes_de_Servicio> Ordenes_de_Servicio { get; set; }
        public virtual DbSet<Proveedore> Proveedores { get; set; }
        public virtual DbSet<Revisiones_Garantia> Revisiones_Garantia { get; set; }
        public virtual DbSet<Servicio> Servicios { get; set; }
        public virtual DbSet<Servicios_Tipos> Servicios_Tipos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tipos_de_Servicio> Tipos_de_Servicio { get; set; }
        public virtual DbSet<Ubicaciones_Taller> Ubicaciones_Taller { get; set; }
        public virtual DbSet<Vehiculo> Vehiculos { get; set; }
        public virtual DbSet<Vehiculos_en_Taller_Ubicacion> Vehiculos_en_Taller_Ubicacion { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
    }
}
