//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_Carros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Servicios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detalle_Servicios()
        {
            this.Detalle_Factura = new HashSet<Detalle_Factura>();
        }
    
        public int ID_Detalle_Servicio { get; set; }
        public int ID_Orden { get; set; }
        public int ID_Servicio { get; set; }
        public string Descripcion_Servicio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Precio_Unitario { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Factura> Detalle_Factura { get; set; }
        public virtual Ordenes_de_Servicio Ordenes_de_Servicio { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
