//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_Carros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Vehiculos
    {
        public int ID_Historial { get; set; }
        public int ID_Vehiculo { get; set; }
        public int ID_Orden { get; set; }
        public System.DateTime Fecha_Visita { get; set; }
        public string Descripcion_Problema { get; set; }
    
        public virtual Ordenes_de_Servicio Ordenes_de_Servicio { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
