//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_Carros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario_Repuestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventario_Repuestos()
        {
            this.Detalle_Repuestos_Orden = new HashSet<Detalle_Repuestos_Orden>();
        }
    
        public int ID_Repuesto { get; set; }
        public string Codigo_Repuesto { get; set; }
        public string Nombre_Repuesto { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad_Stock { get; set; }
        public Nullable<decimal> Precio_Unitario { get; set; }
        public Nullable<int> ID_Proveedor { get; set; }
        public Nullable<System.DateTime> Fecha_Ultima_Entrada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Repuestos_Orden> Detalle_Repuestos_Orden { get; set; }
        public virtual Proveedore Proveedore { get; set; }
    }
}
