//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_Carros.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VentaDeCarrosTallerEntities : DbContext
    {
        public VentaDeCarrosTallerEntities()
            : base("name=VentaDeCarrosTallerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Detalle_Factura> Detalle_Factura { get; set; }
        public virtual DbSet<Detalle_Repuestos_Orden> Detalle_Repuestos_Orden { get; set; }
        public virtual DbSet<Detalle_Servicio> Detalle_Servicio { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Garantia> Garantia { get; set; }
        public virtual DbSet<Historial_Vehiculo> Historial_Vehiculo { get; set; }
        public virtual DbSet<Inventario_Repuesto> Inventario_Repuesto { get; set; }
        public virtual DbSet<Ordenes_de_Servicio> Ordenes_de_Servicio { get; set; }
        public virtual DbSet<Perfil> Perfils { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Revisiones_Garantia> Revisiones_Garantia { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<Servicios_Tipos> Servicios_Tipos { get; set; }
        public virtual DbSet<Tipos_de_Servicio> Tipos_de_Servicio { get; set; }
        public virtual DbSet<Ubicaciones_Taller> Ubicaciones_Taller { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Usuario_Perfil> Usuario_Perfil { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
        public virtual DbSet<Vehiculo_en_Taller_Ubicacion> Vehiculo_en_Taller_Ubicacion { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
    }
}
