//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_Carros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes_de_Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordenes_de_Servicio()
        {
            this.Detalle_Repuestos_Orden = new HashSet<Detalle_Repuestos_Orden>();
            this.Detalle_Servicios = new HashSet<Detalle_Servicios>();
            this.Facturas = new HashSet<Factura>();
            this.Historial_Vehiculos = new HashSet<Historial_Vehiculos>();
        }
    
        public int ID_Orden { get; set; }
        public string Numero_Orden { get; set; }
        public int ID_Vehiculo { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin_Estimada { get; set; }
        public Nullable<System.DateTime> Fecha_Fin_Real { get; set; }
        public Nullable<int> ID_Empleado_Asignado { get; set; }
        public string Estado_Orden { get; set; }
        public string Diagnostico_Inicial { get; set; }
        public string Comentarios_Adicionales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Repuestos_Orden> Detalle_Repuestos_Orden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Servicios> Detalle_Servicios { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historial_Vehiculos> Historial_Vehiculos { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
