//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_Carros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revisiones_Garantia
    {
        public int ID_Revision { get; set; }
        public int ID_Garantia { get; set; }
        public System.DateTime Fecha_Revision { get; set; }
        public string Descripcion_Revision { get; set; }
        public Nullable<int> ID_Empleado_Responsable { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Garantia Garantia { get; set; }
    }
}
