//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_Carros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios_Tipos
    {
        public int ID_Servicio_Tipo { get; set; }
        public int ID_Servicio { get; set; }
        public int ID_Tipo_Servicio { get; set; }
    
        public virtual Servicio Servicio { get; set; }
        public virtual Tipos_de_Servicio Tipos_de_Servicio { get; set; }
    }
}
