//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_Carros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos_en_Taller_Ubicacion
    {
        public int ID_Vehiculo_Ubicacion { get; set; }
        public int ID_Vehiculo { get; set; }
        public int ID_Ubicacion { get; set; }
        public Nullable<System.DateTime> Fecha_Asignacion { get; set; }
    
        public virtual Ubicaciones_Taller Ubicaciones_Taller { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
