//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_Carros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.Garantias = new HashSet<Garantia>();
        }
    
        public int ID_Venta { get; set; }
        public int ID_Vehiculo { get; set; }
        public int ID_Cliente { get; set; }
        public System.DateTime Fecha_Venta { get; set; }
        public Nullable<decimal> Precio_Venta { get; set; }
        public string Numero_Factura_Venta { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Garantia> Garantias { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
