//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_Carros.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VentaDeCarrosTallerEntities2 : DbContext
    {
        public VentaDeCarrosTallerEntities2()
            : base("name=VentaDeCarrosTallerEntities2")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Detalle_Factura> Detalles_Facturas { get; set; }
        public virtual DbSet<Detalle_Repuestos_Orden> Detalles_Repuestos_Ordenes { get; set; }
        public virtual DbSet<Detalle_Servicio> Detalles_Servicios { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Garantia> Garantias { get; set; }
        public virtual DbSet<Historial_Vehiculo> Historial_Vehiculos { get; set; }
        public virtual DbSet<Inventario_Repuesto> Inventario_Repuestos { get; set; }
        public virtual DbSet<Ordenes_de_Servicio> Ordenes_de_Servicios { get; set; }
        public virtual DbSet<Perfil> Perfiles { get; set; }
        public virtual DbSet<Proveedor> Proveedores { get; set; }
        public virtual DbSet<Revisiones_Garantia> Revisiones_Garantias { get; set; }
        public virtual DbSet<Servicio> Servicios { get; set; }
        public virtual DbSet<Servicios_Tipos> Servicios_Tipos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tipos_de_Servicio> Tipos_de_Servicio { get; set; }
        public virtual DbSet<Ubicaciones_Taller> Ubicaciones_Talleres { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Usuario_Perfil> Usuarios_Perfiles { get; set; }
        public virtual DbSet<Vehiculo> Vehiculos { get; set; }
        public virtual DbSet<Vehiculo_en_Taller_Ubicacion> Vehiculos_en_Taller_Ubicacion { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
    }
}
